### ISSUE TITLE
[Feature Proposal] add new StatsAPI function to extract statistics

### ISSUE THREAD

**Issue by babaq** [JuliaStats/HypothesisTests.jl#306] opened 2023-07-29 18:46 UTC
Currently, only `pvalue` and `confint` were proposed and supported by different tests, but sometimes the underlying test statistics were of interest. It would be a more consistent and convenient way to extract statistics by adding new API like `stats`.

**Comment by ararslan** [comment] 2023-07-29 18:54
Duplicate of https://github.com/JuliaStats/HypothesisTests.jl/issues/79 🙂

**Comment by ararslan** [comment] 2023-07-29 19:19
I've finally proposed a solution to that issue, 7 years after opening it: https://github.com/JuliaStats/StatsAPI.jl/pull/24. Feel free to comment there or the original issue if you have further input to provide. Thanks!

**Closed by ararslan** 2023-07-29 19:19 UTC
Labels: duplicate
